# 将来的には対応する規約の読込
inherit_from: .rubocop_todo.yml

# 追加した規約ファイル読込
require:
  - rubocop-rails

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.6
  # 除外
  Exclude:
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 120

#メソッドの長さ指定
MethodLength:
  CountComments: false  # count full line comments?
  Max: 50

# Rubyの循環的複雑度をデフォルト7から変更
CyclomaticComplexity:
  Max: 17

# Railsのファイルパスの記述についてチェックを外す
Rails/FilePath:
  Enabled: false

# Railsのファイルパスの記述についてチェックを外す
Style/BlockComments:
  Enabled: false

# 複数の戻り値に対する return に関しても警告を出さない
RedundantReturn:
  AllowMultipleReturnValues: true
  